---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger Petstore"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /pets:
    get:
      description: "Returns all pets from the system"
      produces:
        - "application/json"
      responses:
        "200":
          description: "A list of pets."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
          examples:
            application/json: |-
              [
                {
                  "id": 101,
                  "name": "Pet 101"
                },
                {
                  "id": 102,
                  "name": "Pet 102"
                }
              ]
  /pets/{petId}:
    get:
      description: "Returns a pet from the system"
      produces:
        - "application/json"
      responses:
        '200':
          description: "A pet."
          schema:
            type: object
            items:
            $ref: '#/definitions/Pet'
          examples:
            application/json: |-
              { "id": 1, "name": "Default Pet" }
definitions:
  Pet:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"